- name: Restart haproxy
  ansible.builtin.service: {name: haproxy, state: restarted, enabled: true}
- name: Restart keepalived
  ansible.builtin.service: {name: keepalived, state: restarted, enabled: true}
